### ISSUE TITLE
Error in Ember 2.8

### ISSUE THREAD

**Issue by ymph** [aupac/ember-aupac-typeahead#23]
Hello,

First thank you very much for this useful ember extension.

I recently tested my application under ember v2.8.0-beta.2 and have the following errors in console wen 
`TypeError: Component.create(...).createElement is not a function.`
I traced that the error comes from the following location [addon/components/aupac-typeahead.js# initializeTypeahead](https://github.com/aupac/ember-aupac-typeahead/blob/master/addon/components/aupac-typeahead.js#L96) when using the `createElement` method.

This seems to comes form the following commit in ember : https://github.com/emberjs/ember.js/pull/13892 that remove the createElement method.

Regards,

ymh

**Comment by ymph** [comment]
Hello,

My issue declaration does not seems to have a lot of success.
Here my current situation.

I have searched quite a lot for a workaround for this problem.
This problem is in fact linked to the possibility of using ember templates outside ember.
When you do a search like "ember template to string" in goggle, you see quite a lot of threads on this subjects. But the solutions given all revolve around 2 or 3 of them. It is also interesting to see the solution evolves with the releases of the ember api (introduction of htmlbar, view -> component,...).
It seems that currently none of these solutions can work with ember 2.8. This way of doing things was never an "official" part of the ember api and the solutions were exploiting some "private" part of the api that have been closed now.

I think this is a real concern for the ember-aupac-typeahead extension, and that a new approach should be taken.

However, if someone know of a solution, I would be very curious an interested to see it.

For my project need, I made a fork and changed the part initializing the `typeahead` to accept something else than an ember template.
In my "consuming" project I then pass either a constant html string, either a underscore template (c.f. http://underscorejs.org/#template).
You can see it in https://github.com/IRI-Research/ember-aupac-typeahead/tree/ember_2.8 . I did not make a Pull Request because this is a really hacky solution only meant for us to move forward.

regards,

ymh

**Comment by jackmatt2** [comment]
Thanks for reporting this, this is a major issue.

**Comment by rwjblue** [comment]
I think the quickest solution here would be to create a DOM element, then use appendTo (instead of createElement).

**Comment by jackmatt2** [comment]
OK, thanks.  I will give this a try.

**Comment by ymph** [comment]
Hello,

Just some observation I made during my attempts to solve this problem:
- appendTo is not part of the ember component official API (
  http://emberjs.com/api/classes/Ember.Component.html). Ember does not offer
  an access to the API documentation of the previous versions, therefore, I
  was unable to determine if it was there before.
- The problem I was not able to solve was in fact to "realize" the newly
  created component, i.e. to find a way to initialize the component element.

regards,

ymh

**Comment by jackmatt2** [comment]
@ymph Have not had time to look at this yet, I will give it a go this weekend probably.

**Comment by smfoote** [comment]
Has there been any progress on this? Anything I can do to help? (This is the last step for my Ember 2.8 upgrade)

**Comment by jackmatt2** [comment]
Have not had time to do anything on this. Will accept a pull request that
solves the issue.

**Comment by smfoote** [comment]
Let me know what you think of #24 - I think there are issues that need to be resolved, but it seems like a reasonable approach, considering how simple the templates are.

**Comment by smfoote** [comment]
Just noticed that this destroys the extensibility of the `suggestionTemplate`. I'll keep investigating.
